---
- name: Configure syslog-ng conf file
  template:
    src: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}-syslog-ng.conf.j2"
    dest: "{{ syslogng_conf_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart syslog-ng