---
- name: Restart syslog-ng
  service:
    name: syslog-ng
    state: restarted

- name: Stop syslog-ng
  service:
    name: syslog-ng
    state: stopped

- name: Start syslog-ng
  service:
    name: syslog-ng
    state: started